# Generated by Django 3.2 on 2022-10-12 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='short_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
