# Generated by Django 3.2 on 2022-10-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_video_short_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.CharField(default='https://img.youtube.com/vi/tSXBdCA-ft8/hqdefault.jpg', max_length=200),
            preserve_default=False,
        ),
    ]
